- name: Configure clean install of fedora cinnamon netinstall
  hosts: localhost
  connection: local
  gather_facts: true
  become: true

  tasks:      
    - name: Install core
      ansible.builtin.yum:
        name: "{{ packages }}"
      vars:
        packages:
        - fedora-workstation-repositories
        - dnf-plugins-core

    - name: Import Microsoft key
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Import Sublime key
      ansible.builtin.rpm_key:
        state: present
        key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg

    - name: Microsoft repo
      ansible.builtin.yum_repository:
        name: vscode-yum
        description: Microsoft repo
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgcheck: yes
        enabled: yes
        repo_gpgcheck: no
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc

    - name: Ensure Google Chrome repository is enabled
      ansible.builtin.yum_repository:
        name: google-chrome
        enabled: yes
        description: Google Chrome Repository
        baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
        gpgcheck: yes
        gpgkey: https://dl.google.com/linux/linux_signing_key.pub

    - name: Sublime repo
      ansible.builtin.yum_repository:
        name: sublime
        description: sublime repo
        baseurl: https://download.sublimetext.com/rpm/stable/x86_64
        enabled: yes

    - name: Add HashiCorp repository
      yum_repository:
        name: hashicorp
        description: HashiCorp Repository
        baseurl: "https://rpm.releases.hashicorp.com/fedora/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/stable"
        enabled: yes
        gpgcheck: no

    - name: Add RPM Fusion free repository
      yum_repository:
        name: rpmfusion-free
        description: RPM Fusion for Fedora Free
        baseurl: https://download1.rpmfusion.org/free/fedora/updates/{{ ansible_distribution_major_version }}/$basearch/
        enabled: yes
        gpgcheck: yes
        gpgkey: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm

    - name: Add RPM Fusion non-free repository
      yum_repository:
        name: rpmfusion-nonfree
        description: RPM Fusion for Fedora Nonfree
        baseurl: https://download1.rpmfusion.org/nonfree/fedora/updates/{{ ansible_distribution_major_version }}/$basearch/
        enabled: yes
        gpgcheck: yes
        gpgkey: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

    - name: Install a list of packages
      ansible.builtin.yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - kernel-headers
        - kernel-devel
        - dkms
        - elfutils-libelf-devel
        - qt5-qtx11extras
        - google-chrome-stable
        - tilix
        - flameshot
        - ulauncher
        - zsh
        - gnome-tweak-tool
        - numix-icon-theme-circle 
        - code
        - cockpit
        - cockpit-machines
        - '@virtualization'
        - '@development-tools'
        - podman
        - git
        - sublime-text
        - crontab
        - pass
        - pass-otp
        - awscli
        - terraform
        - rsyslog

    - name: Install slack rpm
      ansible.builtin.dnf:
        name: https://downloads.slack-edge.com/desktop-releases/linux/x64/4.47.69/slack-4.47.69-0.1.el8.x86_64.rpm
        state: present 
        disable_gpg_check: true

    - name: Set default editor to vim
      ansible.builtin.lineinfile:
        path: /etc/profile
        line: "export EDITOR=vim"

    - name: Remove Thunderbird
      ansible.builtin.dnf:
        name: thunderbird
        state: absent
        autoremove: no
        update_cache: no

    - name: Force remove libreoffice
      ansible.builtin.command: dnf5 remove -y libreoffice*

    - name: Enable service and start Cockpit
      ansible.builtin.service:
        name: cockpit.socket
        enabled: yes
        state: started

    - name: Enable and start libvirtd
      ansible.builtin.service:
        name: libvirtd
        enabled: yes
        state: started

    - name: yum-clean-metadata
      ansible.builtin.command: yum clean all

    - name: Start and enable rsyslog
      ansible.builtin.service:
        name: rsyslog
        state: started
        enabled: true
